### ISSUE TITLE
Internal fermium SDL types exposed without re-export

### ISSUE THREAD

**Issue by cfehunter** [Lokathor/beryllium#120]
Beryllium seems to be exposing fermium types in its public interface.
The example that I've just found is events::Event::Key::{scancode, keycode, modifiers}. SDL_Scancode, SDL_Keycode and SDL_Keymod are imported from fermium and publicly exposed here, without being re-exported.

This seems to make it impossible to handle key events properly, because I can't import the types from Beryllium's private dependency on fermium.

**Comment by Lokathor** [comment]
Oh, yeah that should have a re-export probably.

I can probably get this sorted out later today. In the meantime you can just directly depend on fermium and pull in the type from there.

**Comment by cfehunter** [comment]
Thanks for taking a look. I'm not sure it's quite enough though, they're tuple structs not enums and all of their values are defined as pub constants, which are still not re-exported from fermium.

**Comment by Lokathor** [comment]
yeah rust analyzer was having a flip out because of some Nightly thing so I just stopped working because it was 2am.

thinking about it just a bit, I'm not sure there's a very good way to fix the issue of there being just hundreds of constants that might be needed... I'll probably have to just re-export all the constants? That doesn't seem the best, but a better plan doesn't come to mind.

**Comment by Lokathor** [comment]
released `0.13.1` with these re-exports.
