### ISSUE TITLE
Re-export/expose fermium features for bindgen

### ISSUE THREAD

**Issue by nico-abram** [Lokathor/beryllium#81]

**Comment by Lokathor** [comment]
The build of beryllium might break if you do that, because some of what bindgen generates is platform specific stuff.

If there's a platform that you want beryllium support for, you should run fermium's bindings generation process and then submit that output as a new pre-generated platform as a PR to fermium (possibly with expanded CI files as well so that it can be regularly checked).

**Comment by Lokathor** [comment]
Well, I'm going to close this because you can always already specify 

```
--features="fermium/use_bindgen_bin"
```

when you run `cargo build`
